### ISSUE TITLE
git

### ISSUE THREAD

**Issue by tim-faase** [alekseykuleshov/commweb#1]
Suggest you gitignore the .git folder that's included in the composer repo

**Comment by alekseykuleshov** [comment]
@tim-faase The.git folder is created because when composer uses the dev-master(latest commit) it clones the git repo (including the .git folder). I'll release the version and update the README to use it.

**Comment by alekseykuleshov** [comment]
@tim-faase Done. `.git` is not added when installing using

```
{
    "require": {
        "atdev/commweb": "0.1.0"
    }
}
```
